---
title: "​Artificial​ ​Intelligence​ ​in​ ​Healthcare:​ ​History,​ ​Clinical​ ​and​ ​Research​ ​Applications,​ ​Current Landscape,and Challenges​"
---
## Presentation File
- [Link](https://docs.google.com/presentation/d/1oeVGTj_OsuxvnHRrp9pZ7cMn0GfCk38VWmK-VjRKSFA/edit?usp=sharing)

## Resources and references
-  https://www.openevidence.com/announcements/openevidence-ai-first-ai-score-above-90-percent-on-the-usmle
 [Link]( https://www.openevidence.com/announcements/openevidence-ai-first-ai-score-above-90-percent-on-the-usmle
)

- https://www.coatue.com/blog/press/partnering-with-openevidence [Link](https://www.coatue.com/blog/press/partnering-with-openevidence)

- “CPH 100 / Data C146: Foundations of Computational Precision Health”, UC Berkeley, Fall 2025 [Link](https://irenechen.net/cph100/)

- Clarity [Link](https://clairity.com/)

- Mirai [Link](https://jclinic.mit.edu/mirai/)

- “Risk Reduction and Early Detection: Updates on Breast Cancer Screening with Dr. Connie Lehman ” [LINK](https://www.youtube.com/watch?v=y_Oq7f5MIX8)

- "Developing next-generation cancer care management with multi-agent orchestration" [Link](https://www.microsoft.com/en-us/industry/blog/healthcare/2025/05/19/developing-next-generation-cancer-care-management-with-multi-agent-orchestration/)

- "Evolution Of Neural Network" [Link](https://sefiks.com/2017/10/14/evolution-of-neural-networks/)

- “6.7930[6.871]/HST.956: Machine Learning for Healthcare”, MIT University, Spring 2025 [Link](https://mlhcmit.github.io/)

- “UvA Foundation Models Course” , Cees Snoek, Yuki Asano , Spring 2024 Link [Link](https://uvafomo.github.io/)

- “AI Agents vs Agentic AI Systems" [Link](https://research.aimultiple.com/ai-agents-vs-agentic-ai/)

- AI-READI [Link](https://aireadi.org/)

- Artificial Intelligence in Precision Medicine for Diabetes and Other Chronic Diseases, Day 2 [Link](https://www.youtube.com/watch?v=3VXsntmHzWU)

- The Human Phenotype Project [Link](https://humanphenotypeproject.org/)

- Lee Reicher et al., “Deep phenotyping of health–disease continuum in the Human Phenotype Project”, nature medicine (2025)

- Guy Lutsker et al., “From Glucose Patterns to Health Outcomes: A Generalizable Foundation Model for Continuous Glucose Monitor Data Analysis”, arxiv (2024)

- Divya Shanmugam et al., “Generative Artificial Intelligence in Medicine”, Annual Review of Biomedical Data Science (2025)

- Marcus A. Badgeley et al., “Deep learning predicts hip fracture using confounding patient and healthcare variables”, npj digital medicine (2019)

- Ziad Obermeyer et al., “Dissecting racial bias in an algorithm used to manage the health of populations”, science, 2019

- “CS 329T: Trustworthy Machine Learning , Large Language Models and Applications”, Stanford, Fall 2023

- Introducing the Next Generation of Vectara's Hallucination Leaderboard [Link](https://www.vectara.com/blog/introducing-the-next-generation-of-vectaras-hallucination-leaderboard)

- Technically Accurate, Medically Fatal [Link](https://nodesian.medium.com/technically-accurate-medically-fatal-a3bbbc7c27cc)

- Gemini 3.0 Pro Surpasses Radiology Trainees on Radiology's Last Exam (RadLE) [Link](https://drdattaaiims.github.io/Gemini-3.0-Radiology-2025.html)

- Arthur Brant et al. “Performance of a Deep Learning Diabetic Retinopathy Algorithm in India”, JAMA Network Open (2025)

- https://a2zradiology.ai/ [Link](https://a2zradiology.ai/) 

- Advancing medical AI with Med-Gemini [Link](https://research.google/blog/advancing-medical-ai-with-med-gemini/)

- AMIE: A research AI system for diagnostic medical reasoning and conversations [Link](https://research.google/blog/amie-a-research-ai-system-for-diagnostic-medical-reasoning-and-conversations/)

- OWKIN MSIntuit® CRC [Link](https://www.owkin.com/diagnostics/msintuit-crc)

- The Dawn of Spatial Medicine [Link](https://erictopol.substack.com/p/the-dawn-of-spatial-medicine)

- Thierry M. Nordmann et al., “Spatial proteomics identifies JAKi as treatment for a lethal skin disease”, nature(2024)

- Zhuoting Zhu et al., “Oculomics: Current concepts and evidence”, Progress in Retinal and Eye Research (2025)

- Reti-CVD [Link](https://mediwhale.com/drnoon-cvd/ )

- AI in Medical Education Symposium, Stanford university, 2025 [Link](https://www.youtube.com/playlist?list=PLuP5qOnCjJ-6N6gfS0CLltvlLFul9pl8I)

- Precision Medicine 2024: Education in the AI Era, Harvard University, 2024, [Link](https://www.youtube.com/playlist?list=PLDf0t9MNzNSpFd0xB_Eca9YBemV3kpk1D)

- E. Abdulnour et al., “Educational Strategies for Clinical Supervision of Artificial Intelligence Use”, The New England Journal of Medicine, 2025

- AI Clinical Coach [Link](https://med.stanford.edu/edtech/portfolio/ai-clinical-coach.html)

- DDx [Link](https://educators.sketchy.com/)

- AlphaFold [Link](https://deepmind.google/science/alphafold/)

- Zuojun Xu, “A generative AI-discovered TNIK inhibitor for idiopathic pulmonary fibrosis: a randomized phase 2a trial”, nature medicine (2025)

- Eileen Kim, “AI Scribes Are Not Productivity Tools (Yet)”, Nejm AI (2025)

- Hugo™ RAS System [Link](https://www.medtronic.com/covidien/en-gb/robotic-assisted-surgery/hugo-ras-system.html)

- Healthcare AI in 2025 – a reflection [Link](“https://janbeger.substack.com/p/healthcare-ai-in-2025-a-reflection”)

- The most interesting scientific papers I read last month , Jan Berger [Link](https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7016868239498444800)

- The 2025 Physicians AI Report [Link](https://2025-physicians-ai-report.offcall.com/)


## Further resources 

- “ML/DL in Healthcare and Biomedicine Courses” [Link](aimed_courses.qmd)



