---
title: "Foundation Models"
---
## Presentation File
- [Link](https://docs.google.com/presentation/d/19sE-bt1NH_s_mPhu2sbbzIXOrga2tnvOAeKOp5XiY3c/edit?usp=sharing)

## Resources and references
- “Foundational Robustness of Foundation Models” , NeurIPS 2022 Tutorial [Link](https://neurips.cc/virtual/2022/tutorial/55796)

- "Foundation Models" , Samuel Albanie, Online Course 2022 [Link](https://samuelalbanie.com/teaching/2022-foundation-models)

- "UvA Foundation Models Course" , Cees Snoek, Yuki Asano , Spring 2024 [Link](https://uvafomo.github.io/)

- "CS 886: Recent Advances on Foundation Models",  Wenhu Chen, University of Waterloo, Winter 2024 [Link](https://cs.uwaterloo.ca/~wenhuche/teaching/cs886/)

- "CS 8803 VLM Vision-Language Foundation Models", Zsolt Kira, Georgia Tech, Fall 2024 [Link](https://faculty.cc.gatech.edu/~zk15/teaching/AY2024_cs8803vlm_fall/index.html)

- "BIODS 271: Foundation Models for Healthcare" ,Stanford University, Winter 2024 [Link](https://stanford-biods271.github.io/)

- "Emergence of Foundation Models: Opportunities to Rethink Medical AI", Shekoofeh Azizi, CVPR 2024 [Link](https://www.youtube.com/watch?v=zoKr60f-Kws)

- "COMP 590/776: Computer Vision in 3D World", Roni Senguptam UNC, Spring 2023 [Link](https://www.cs.unc.edu/~ronisen/teaching/spring_2023/COMP776_Vision_spring23.html)

- "COS 597G: Understanding Large Language Models" , Danqi Chen, Princeton University, Fall 2022 [Link](https://www.cs.princeton.edu/courses/archive/fall22/cos597G/)

- "UVA Deep Learning Course", Yuki Asano , Fall 2022 [Link](https://uvadlc.github.io/lectures-nov2022.html#)

- "What are Foundation Models in AI?", https://www.youtube.com/watch?v=dV0X1QyLL8M [Link](https://www.youtube.com/watch?v=dV0X1QyLL8M)

- "CS25: Transformers United V4", Stanford University, Spring 2024 [Link](https://web.stanford.edu/class/cs25/)

- J. Devlin et al., "Bert: Pre-training of deep bidirectional transformers for language understanding", NAACL-HLT (2019)

- T. Brown et al., "Language models are few-shot learners", NeurIPS (2020)

- J. Kaplan et al., "Scaling laws for neural language models", arxiv (2020)

- A. Dosovitskiy, et al. "An image is worth 16x16 words: Transformers for image recognition at scale", ICLR (2021)

- R. Bommasani et al., "On the opportunities and risks of foundation models", arxiv (2021)

- A. Vaswani et al., "Attention is all you need", NeurIPS (2017)

- M. Chen et al., "Evaluating large language models trained on code", arxiv (2021)

- A. Radford et al., "Learning transferable visual models from natural language supervision", ICML (2021)

- J Wei et al., "Emergent Abilities of Large Language Models", arxiv (2022)

- T. Chen et al., "A simple framework for contrastive learning of visual representations", ICML (2020)

- R. Schaeffer et al., "A simple framework for contrastive learning of visual representations", NeurIPS (2023)

- Z. Huang et al., "A visual–language foundation model for pathology image analysis using medical Twitter",  nature medicine (2023)

- A. Kirillov et al., "Segment Anything", arxiv (2023)

- Med-Gemini: Advancing medical AI with Med-Gemini, (2024) [Link](https://research.google/blog/advancing-medical-ai-with-med-gemini/)

## Further resources and references

- "CS 324 - Advances in Foundation Models" , Stanford University, Winter 2023 [Link](https://stanford-cs324.github.io/winter2023/)

- "CS 839 - Foundation Models & the Future of Machine Learning" , Wisconsin–Madison University, Fall 2023 [Link](https://pages.cs.wisc.edu/~fredsala/cs839/fall2023/index.html)

- "MIT FUTURE OF AI 6.S087: Foundation Models & Generative AI", 2024, [Link](https://www.futureofai.mit.edu/)

- "AI Foundation Models CPSC 488/588" , Fall 2023 , Yale University [Link](https://yale-nlp.github.io/cpsc488/)

- "EE/CS 148 - Large Language and Vision Models", Caltech, Spring 2024 [Link](https://gkioxari.github.io/teaching/cs148/)

- "CVPR 2024 Tutorial on "Recent Advances in Vision Foundation Models", [Link](https://vlp-tutorial.github.io/)

- "CS 601.471/671 NLP: Self-supervised Models", Johns Hopkins University - Spring 2024, [Link](https://self-supervised.cs.jhu.edu/sp2024/)

- "ECCV 2022 Tutorial on Self-Supervised Representation Learning in Computer Vision", [Link](https://feichtenhofer.github.io/eccv2022-ssl-tutorial/)

- "Self-Supervised Representation Learning", Lilian Weng, [Link](https://lilianweng.github.io/posts/2019-11-10-self-supervised/)

- "CIS 7000 - Large Language Models", University of Pennsylvania, Fall 2024, [Link](https://llm-class.github.io/)

- "CS 2281R: Mathematical & Engineering Principles for Training Foundation Models", Harvard University , Fall 2024, [Link](https://shamulent.github.io/CS_2281_2024.html)